### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by PoRa-dayo** [jiangnangame/PvZ-Travel-Bugs-Report#10]
Statues that are on top of Speed Tiles seem to be ignored by plants. Straight-shot projectiles like peas and bombs from Bomb-shroom also pass through those statues.

**Comment by AngelShadow2017** [comment]
> Statues that are on top of Speed Tiles seem to be ignored by plants. Straight-shot projectiles like peas and bombs from Bomb-shroom also pass through those statues.

why it can be on top of speed tile and i will check it

**Comment by PoRa-dayo** [comment]
Because Sculptor Zombies exist lmao

**Comment by AngelShadow2017** [comment]
solved in my computer, You can see it was fixed in next version
