### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by AngelShadow2017** [jiangnangame/PvZ-Travel-Bugs-Report#138]
![Screenshot_20220612_182953_com tencent mobileqq](https://user-images.githubusercontent.com/32807696/173229042-f2c9bf1c-1a85-4cc0-a024-06134647f041.jpg)
![Screenshot_20220612_182957_com tencent mobileqq](https://user-images.githubusercontent.com/32807696/173229045-bbb5eabe-a993-45b6-a8c9-6e1c929f5d5a.jpg)

**Comment by WU-SUNFLOWER** [comment]
fixed
