### ISSUE TITLE
PVZTR not working

### ISSUE THREAD

**Issue by Domiro23** [jiangnangame/PvZ-Travel-Bugs-Report#146]
Hello, i have a problem that PVZTR doesn't work. When i open the game, it says that the web isn't available, is the game temporalily closed or is there something else? It has been like this for 6 days now

**Comment by AngelShadow2017** [comment]
if you are willing to play it on your mobile phone then we are trying to solve it :(

**Comment by AngelShadow2017** [comment]
here's the link to join our discord.
https://discord.gg/5UZggBD3Uk

**Comment by Domiro23** [comment]
Ok, thank you

**Comment by AngelShadow2017** [comment]
that's ok
