### ISSUE TITLE
[ANNOUNCEMENT] Regarding PvZTR website being down

### ISSUE THREAD

**Issue by PoRa-dayo** [jiangnangame/PvZ-Travel-Bugs-Report#149]
Yes, we know that the official website (http://pvz.jiangnangame.com/) has already been down for a week straight outside of mainland China, and probably for even more days to come.

The alternative itch.io page however, is still there. You can still download and play the latest official version in Offline Mode from there.
https://angel-shadow.itch.io/pvz-travel

The itch.io page also contains the link to our Discord. You can go there to ask for help. We're also posting test versions of the upcoming update on the Discord server for you to try out and give feedbacks.

**Comment by AngelShadow2017** [comment]
我收到了
