### ISSUE TITLE
What's this

### ISSUE THREAD

**Issue by PoRa-dayo** [jiangnangame/PvZ-Travel-Bugs-Report#15]
This always shows up whenever you beat Zombot Snowy Owl One for some reason. Seems to have no other abnormalities other than this message.
![Screenshot 2021-11-20 22 19 03](https://user-images.githubusercontent.com/62925753/142880320-41ffe770-c94e-41b3-82fa-74b45cb72d7c.png)

**Comment by AngelShadow2017** [comment]
get

**Comment by AngelShadow2017** [comment]
fixed in my computer
