### ISSUE TITLE
how do you call yourself a programmer if a single player is able to detect bugs every single day lol jk

### ISSUE THREAD

**Issue by PoRa-dayo** [jiangnangame/PvZ-Travel-Bugs-Report#18]
The funny nuclear bird music still plays when losing Danmaku Fantasy Extra  - Final Night (The one with the boss).
Restarting by pressing the restart button on losing screen will have the music overlap.

**Comment by AngelShadow2017** [comment]
Already knows when i program this level so I wont fix
