### ISSUE TITLE
New bug

### ISSUE THREAD

**Issue by PoRa-dayo** [jiangnangame/PvZ-Travel-Bugs-Report#181]
In Swamp 12 cutscene, spam the down button and you'll be stuck in that cutscene forever, fun.

Music looping error in the seasonal extra hidden level (wooden bridge). This also makes you stuck on the level forever after finishing the level.

Buttered or frozen zombies don't play their death animations when killed by Bowling Wall-nuts.

Zombies spawning from the ground right at plants’ positions sometimes don’t play their eating animations but play their walking animations instead.

**Comment by AngelShadow2017** [comment]
what's the picture

**Comment by AngelShadow2017** [comment]
我收到了
