### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by PoRa-dayo** [jiangnangame/PvZ-Travel-Bugs-Report#20]
I was checking Foggy City Day 9 on banned plants route again, and apparently when I try to restart or quit the level this pops up
![Screenshot 2021-11-25 23 41 26](https://user-images.githubusercontent.com/62925753/143478208-8831719c-67c1-4f70-8122-432c257402f0.png)
.

**Comment by AngelShadow2017** [comment]
no just too many elements
