### ISSUE TITLE
a

### ISSUE THREAD

**Issue by PoRa-dayo** [jiangnangame/PvZ-Travel-Bugs-Report#21]
Chinese New Year Challenge 2019 - 3 keeps showing this message. When the level is finished it's stuck, no star comes out.
![Screenshot 2021-11-30 22 11 11](https://user-images.githubusercontent.com/62925753/144074473-fc471336-916d-4ad2-a9f8-ad74143d7d96.png)
![Screenshot 2021-11-30 22 15 44](https://user-images.githubusercontent.com/62925753/144074485-2e291f84-941e-412e-86d4-76c17b6ec2b2.png)

**Comment by AngelShadow2017** [comment]
dont want to fix
