### ISSUE TITLE
离线模式bug

### ISSUE THREAD

**Issue by ojj011** [jiangnangame/PvZ-Travel-Bugs-Report#221]
安卓在离线模式，冒险16关打着打着会卡死，等待一会就会闪退。会不会在出僵尸的时候有什么问题?

**Comment by AngelShadow2017** [comment]
截个图发一下

**Comment by AngelShadow2017** [comment]
> 安卓在离线模式，冒险16关打着打着会卡死，等待一会就会闪退。会不会在出僵尸的时候有什么问题?

截一下图，有报错吗

**Comment by ojj011** [comment]
手机是vivos5，存储空间是够的，其他关卡没有问题

**Comment by ojj011** [comment]
并没有报错，直接卡死

**Comment by AngelShadow2017** [comment]
> 手机是vivos5，存储空间是够的，其他关卡没有问题

一直都出现吗

**Comment by ojj011** [comment]
已经两次了，我再试试

**Comment by AngelShadow2017** [comment]
闪退是什么情况

**Comment by AngelShadow2017** [comment]
![Screenshot_20230407_233645_com android chrome](https://user-images.githubusercontent.com/32807696/230636535-e76e5804-3259-4744-a2f4-dcd6da11bfc0.jpg)
我这边可以正常通关的，请检查你的离线包是否是四月的版本

**Comment by AngelShadow2017** [comment]
最新版的在线版和离线版应该没有区别

**Comment by AngelShadow2017** [comment]
我先睡觉了，你把状况发个截图吧。

**Comment by ojj011** [comment]
![Uploading IMG_20230407_233711.jpg…]()
这次没有卡死，但也卡顿的现象发生，卡顿了三次，我都截屏了。前两次都是出现卡顿，然后卡死，最后闪退

**Comment by AngelShadow2017** [comment]
那确实和手机性能有关系。

**Comment by AngelShadow2017** [comment]
用电脑玩会好很多

**Comment by ojj011** [comment]
我看的b站视频下载的，使用的2月离线包。我更新一下试试
![IMG_20230407_233711](https://user-images.githubusercontent.com/120115429/230637389-c09298b6-98f5-4add-a54c-09c7175a0078.jpg)
刚才图片没发出来

**Comment by ojj011** [comment]
麻烦了，应该就是离线包的问题
