### ISSUE TITLE
Speed Suggestion

### ISSUE THREAD

**Issue by AngelShadow2017** [jiangnangame/PvZ-Travel-Bugs-Report#33]
![Screenshot_2021-12-19_21 59 54](https://user-images.githubusercontent.com/32807696/146692836-aa4f219a-c2c6-4753-8023-703a6d6e3594.png)

**Comment by PoRa-dayo** [comment]
Speed imo can be 1, 1.5, 2, 3 and 5 (2.5 feels useless, 10 is just there for the funny so it doesn't hurt to remove it)

**Comment by AngelShadow2017** [comment]
ok
