### ISSUE TITLE
Just summarizing all the pending suggestions so far

### ISSUE THREAD

**Issue by PoRa-dayo** [jiangnangame/PvZ-Travel-Bugs-Report#42]
- [From Leo] Make the screen flash red shortly after the player uses a "banned" plant and enters the hard route (similar to how Deltarune plays a sound when the player aborts the Snowgrave route)
- Make some seed packets red in level 109 and put a different alert box for them.
- Nerf level 109 and Winter Extra Night 4
- Zomboss in Winter Extra Night 5 still occasionally makes the level impossible to beat (e.g. Zomboss shoots funny missiles that destroy all your 5 Winter Aloes like 10 seconds after you've just planted them, or suddenly spawns way too many zombies at the start)
- Add hotkeys

**Comment by AngelShadow2017** [comment]
no way
