### ISSUE TITLE
wind sound

### ISSUE THREAD

**Issue by PoRa-dayo** [jiangnangame/PvZ-Travel-Bugs-Report#43]
After losing a level that plays the chilling wind sound throughout the level (e.g. Winter Extra), the chilling wind sound still plays if you choose to exit the level

This bug isn't fixed so I'm gonna repost it here: When you set the game at 3x speed, and speed is automatically set to 1x again after zombie reaches lawnmower and stuff, the speed in speed setting is still 3x despite the game going at 1x

**Comment by AngelShadow2017** [comment]
i have fixed

**Comment by AngelShadow2017** [comment]
a month ago
