### ISSUE TITLE
Speed Tiles pushing Crystals forward (in fanmade levels)

### ISSUE THREAD

**Issue by PoRa-dayo** [jiangnangame/PvZ-Travel-Bugs-Report#57]
![Screenshot 2022-01-20 23 51 18](https://user-images.githubusercontent.com/62925753/150384500-f007e806-b028-4236-bbd3-a26505579e09.png)
![Screenshot 2022-01-20 23 51 20](https://user-images.githubusercontent.com/62925753/150384508-2c657db4-ce7c-4a9a-884d-39fb20e1c330.png)

**Comment by AngelShadow2017** [comment]
ok fucking

**Comment by AngelShadow2017** [comment]
idont have this
